openapi: 3.0.3
info:
  title: TIE Fighters API
  version: 1.0.0
  description: API for managing TIE Fighter ships
servers:
  - url: /
paths:
  /:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello:
                    type: string
                    example: world
  /tie-fighters:
    get:
      summary: Get all TIE fighters
      responses:
        '200':
          description: List of TIE fighters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ship'
        '400':
          description: Resource not found
        '500':
          description: Server error
    post:
      summary: Create a new TIE fighter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - data
              properties:
                data:
                  $ref: '#/components/schemas/ShipInput'
      responses:
        '201':
          description: Ship created successfully
          content:
            application/json:
              schema:
                type: string
                description: Ship ID
        '500':
          description: Server error
  /tie-fighters/{id}:
    get:
      summary: Get a specific TIE fighter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: TIE fighter details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ship'
        '500':
          description: Server error
  /tie-fighters/{id}/land:
    put:
      summary: Land a TIE fighter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ship landed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ship'
        '500':
          description: Server error
  /tie-fighters/{id}/shoot:
    put:
      summary: Make a TIE fighter shoot
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Ship shot successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ship'
        '500':
          description: Server error
components:
  schemas:
    Ship:
      type: object
      properties:
        id:
          type: string
        model:
          type: string
        bullets:
          type: integer
        landed:
          type: boolean
        pilot:
          type: string
        alias:
          type: string
    ShipInput:
      type: object
      properties:
        model:
          type: string
        bullets:
          type: integer
        landed:
          type: boolean
        pilot:
          type: string
        alias:
          type: string